{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "airbud.fullname" . }}-selfsigned
  labels:
    {{- include "airbud.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end -}}
