# 1. Shared Data (Models, Charts, Uploads)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart-rag.fullname" . }}-shared-data
spec:
  accessModes:
    - {{ .Values.sharedData.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sharedData.size }}
  storageClassName: {{ .Values.global.storageClass }}
---
# 2. Postgres Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart-rag.fullname" . }}-postgres-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  storageClassName: {{ .Values.global.storageClass }}
---
# 3. Neo4j Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart-rag.fullname" . }}-neo4j-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.neo4j.storage }}
  storageClassName: {{ .Values.global.storageClass }}