apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-rag.fullname" . }}-env
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
type: Opaque
stringData:
  # --- Passwords & Tokens ---
  POSTGRES_PASSWORD: {{ .Values.global.secrets.postgresPassword | quote }}
  NEO4J_PASSWORD: {{ .Values.global.secrets.neo4jPassword | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.global.secrets.grafanaPassword | quote }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.global.secrets.influxToken | quote }}
  
  # --- Common Env Vars ---
  POSTGRES_USER: "rag_user"
  POSTGRES_DB: "rag_db"
  # Note: Internal K8s DNS name for the Postgres Service
  POSTGRES_SERVER: "{{ include "smart-rag.fullname" . }}-postgres"
  
  # Neo4j Settings
  NEO4J_URI: "bolt://{{ include "smart-rag.fullname" . }}-neo4j:7687"
  NEO4J_USER: "neo4j"