{{- if not .Values.global.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airbud.fullname" . }}-env
  labels:
    {{- include "airbud.labels" . | nindent 4 }}
type: Opaque
stringData:
  # --- Passwords & Tokens ---
  POSTGRES_PASSWORD: {{ .Values.global.secrets.postgresPassword | quote }}
  NEO4J_PASSWORD: {{ .Values.global.secrets.neo4jPassword | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.global.secrets.grafanaPassword | quote }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.global.secrets.influxToken | quote }}
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ .Values.global.secrets.influxdbPassword | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.global.secrets.pgadminPassword | quote }}
  GROQ_API_KEY: {{ .Values.global.secrets.groqApiKey | quote }}
  SANCTUARY_API_KEY: {{ .Values.global.secrets.sanctuaryApiKey | quote }}
{{- end -}}