apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbud.fullname" . }}-gateway
  annotations:
    {{- with .Values.gateway.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "airbud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      {{- if eq .Values.gateway.service.type "NodePort" }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
  selector:
    {{- include "airbud.labels" . | nindent 4 }}
    component: gateway