apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-rag.fullname" . }}-gateway
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 443
      protocol: TCP
      name: https
      {{- if .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
  selector:
    {{- include "smart-rag.labels" . | nindent 4 }}
    component: gateway