apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbud.fullname" . }}-oauth2-proxy
  labels:
    {{- include "airbud.labels" . | nindent 4 }}
    component: oauth2-proxy
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    {{- include "airbud.selectorLabels" . | nindent 4 }}
    component: oauth2-proxy
