{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "smart-rag.fullname" . }}-postgres
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
    component: postgres
spec:
  serviceName: {{ include "smart-rag.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "smart-rag.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "smart-rag.selectorLabels" . | nindent 8 }}
        component: postgres
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
              name: postgres
          env:
            # We use a subdirectory to avoid permission issues with lost+found on some storage classes
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: "rag_user"
            - name: POSTGRES_DB
              value: "rag_db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "smart-rag.fullname" . }}-env
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rag_user
                - -d
                - rag_db
            initialDelaySeconds: 15
            periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "smart-rag.fullname" . }}-postgres-data
{{- end }}