 {{- if .Values.neo4j.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "airbud.fullname" . }}-neo4j
  labels:
    {{- include "airbud.labels" . | nindent 4 }}
    component: neo4j
spec:
  serviceName: {{ include "airbud.fullname" . }}-neo4j
  replicas: 1
  selector:
    matchLabels:
      {{- include "airbud.selectorLabels" . | nindent 6 }}
      component: neo4j
  template:
    metadata:
      labels:
        {{- include "airbud.selectorLabels" . | nindent 8 }}
        component: neo4j
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: neo4j
          image: "{{ .Values.neo4j.image }}"
          resources:
            {{- toYaml .Values.neo4j.resources | nindent 12 }}
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: RAG_NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "airbud.secretName" . }}
                  key: NEO4J_PASSWORD
            - name: NEO4J_AUTH
              value: "neo4j/$(RAG_NEO4J_PASSWORD)"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: {{ .Values.neo4j.env.heapInitial | default "512m" | quote }}
            - name: NEO4J_dbms_memory_heap_max__size
              value: {{ .Values.neo4j.env.heapMax | default "1G" | quote }}

          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - cypher-shell -u neo4j -p $RAG_NEO4J_PASSWORD "RETURN 1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 30
            periodSeconds: 10
            
      # --- KARPENTER CONFIG ---
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      volumes:
        - name: neo4j-data
        {{- if .Values.global.persistence.enabled }}
          persistentVolumeClaim:
            # References the standalone PVC in pvc.yaml
            claimName: {{ include "airbud.fullname" . }}-neo4j-data
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}