{{- if .Values.neo4j.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "smart-rag.fullname" . }}-neo4j
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
    component: neo4j
spec:
  serviceName: {{ include "smart-rag.fullname" . }}-neo4j
  replicas: 1
  selector:
    matchLabels:
      {{- include "smart-rag.selectorLabels" . | nindent 6 }}
      component: neo4j
  template:
    metadata:
      labels:
        {{- include "smart-rag.selectorLabels" . | nindent 8 }}
        component: neo4j
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: neo4j
          image: "{{ .Values.neo4j.image }}"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/$(NEO4J_PASSWORD)"
            # Heap settings for performance
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "1G"
          envFrom:
            - secretRef:
                name: {{ include "smart-rag.fullname" . }}-env
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - cypher-shell -u neo4j -p $NEO4J_PASSWORD "RETURN 1"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: {{ include "smart-rag.fullname" . }}-neo4j-data
{{- end }}